services:
  - type: web
    name: textile_web
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn textile_project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
